- name: apply basic and common roles
  # strategy: debug
  hosts: localhost
  pre_tasks:
  - name: Inform the team of the start
    slack:
      msg: "Start CI server deployment on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total }} MB of RAM "
      color: normal
      link_names: 0
      token: "{{ slack_token }}"
      username: "Orchy McConfigface on {{ inventory_hostname }}"
    tags:
    - slack
  roles:
  - { role: brucellino.docker, become: true }
  post_tasks:
  - name: Inform the team of the end of docker provisioning
    slack:
        token: "{{ slack_token }}"
        username: "Orchy McConfigface on {{ inventory_hostname }}"
        color: good
        parse: full
        link_names: 1
        msg: "CI Server now has docker on it :whale:"
        validate_certs: yes