- name: apply basic and common roles
  # strategy: debug
  hosts: localhost
  pre_tasks:
  - name: Inform the team of the start
    slack:
      msg: "Start CI server deployment on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total }} MB of RAM "
      color: normal
      link_names: 0
      token: "{{ slack_token }}"
      username: "Orchy McConfigface on {{ inventory_hostname }}"
    tags:
    - slack
  roles:
  