- name: Ensure docker is present
  hosts: jenkins-hosts
  pre_tasks:
  - name: Inform the team of the start
    slack:
      msg: "Start CI server deployment on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total }} MB of RAM "
      color: normal
      link_names: 0
      token: "{{ slack_token }}"
      username: "Orchy McConfigface on {{ ansible_hostname }}"
    tags:
    - slack
  roles:
  - { role: brucellino.docker, become: true }
  post_tasks:
  - name: Inform the team of the end of docker provisioning
    slack:
      token: "{{ slack_token }}"
      username: "Orchy McConfigface on {{ inventory_hostname }}"
      color: good
      parse: full
      link_names: 1
      msg: "CI Server now has docker on it :whale:"
      validate_certs: yes
    tags:
      - slack

- name: Deploy Jenkins
  hosts: jenkins-hosts
  pre_tasks:
    - name: Inform the team of the start
      slack:
        msg: "Start CI server deployment on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total }} MB of RAM "
        color: normal
        link_names: 0
        token: "{{ slack_token }}"
        username: "Orchy McConfigface on {{ inventory_hostname }}"
      tags:
        - slack
  tasks:
    - name: Ensure deploy dir is present
      file:
        path: /deploy
        force: no
        unsafe_writes: no
        group: root
        state: directory
        mode: "g+rwx"
        owner: root
        follow: yes
    - name: Copy the docker configs
      copy:
        src: ../Docker/
        dest: /deploy/
        directory_mode: yes
        force: yes
        remote_src: no
        group: root
        owner: root