- name: apply basic and common roles
  # strategy: debug
  hosts: localhost
  tasks:
  - name: Inform the team of the start
    slack:
      msg: "Starting CODE-RADE CI deployment. on {{ inventory_hostname }}. This baby has {{ ansible_processor_count }} CPUs and {{ ansible_memory_mb.real.total // 1000 }} GB of RAM "
      # channel: coderade # the channel is encoded in the token.
      color: normal
      link_names: 0
      token: "{{ slack_token }}"
      username: "Orchy McConfigface on {{ inventory_hostname }}"
    tags:
    - slack