---
# Jenkins Config as Code
# See https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md
# and https://plugins.jenkins.io/configuration-as-code
# ----- #
# Core Jenkins configuration - authn/z, executors, clouds
jenkins:
  authorizationStrategy: unsecured
  systemMessage: |
    This is the best of all possible system messages
  securityRealm:
    local:
      users:
        - id: admin
          password: password
  numExecutors: 3
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/slave"
              volumes:
                - hello:/hello
                - world:/world
              environmentsString: |
                hello=world
                foo=bar
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
# Miscellaneous configuration outside of core Jenkins configuration
# Some of these are plugin-dependent.
unclassified:
  location:
    url: http://2c75b714.ngrok.io
    adminAddress: admin@admin.com
  # slackNotifier: # Slack notification plugin configuration
  #   teamDomain: cicddemo-miguelnge
  #   tokenCredentialId: slack-token

# Credentials configured for interacting with external services
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: slack-token
              secret: '${SLACK_TOKEN}'
              description: Slack token
